### ISSUE TITLE
First meetup! 

### ISSUE THREAD

**Issue by nuke-web3** [ProtoSchool/Denver#3]
Join us in our **first meetup**!!! :rocket: :moon: 

[RVSP ON MEETUP.COM HERE](https://www.meetup.com/Blockchain-Developers-United-Denver/events/257761113/)

We are joining forces with *Blockchain Developers United - Denver* to start off our adventures together :grinning: 

Looking forward to this!

**Comment by nuke-web3** [comment]
Slides for the intro presentation: https://docs.google.com/presentation/d/1FbMjmHQSGKx7WLYEkk5zr3Fl1P6AQnxZYbZi5n-Bmd4/edit?usp=sharing

**Comment by terichadbourne** [comment]
@NukeManDan If you take any photos tonight that attendees are comfortable sharing, feel free to tag @ProtoSchool on Twitter and we can help share!

**Comment by nuke-web3** [comment]
Absolutely. I got a nicer camera to do some media production - but we will see how many show up - big snow in Denver today :crossed_fingers:  - roads are iffy.

**Comment by nuke-web3** [comment]
For others seeing this thread - flow the school here: https://twitter.com/ProtoSchool
:tada:

**Comment by nuke-web3** [comment]
Thanks for coming all!

@grizzeley @ryanbriley @nward13

Bigger and better for the next one for sure. :rocket: It was a great first one!
