### ISSUE TITLE
Code of Conduct update - need contacts for conflict of interest

### ISSUE THREAD

**Issue by nuke-web3** [ProtoSchool/Denver#4]
https://github.com/ProtoSchool/Denver/blob/master/CODE_OF_CONDUCT.md

Updated with contact info link to the README.md

@terichadbourne  - I have you listed in case of a conflict of interest, but who else should be listed? And if for some crazy reason we would need to escalate to another person/party at protocol.ai - who would the person be? 

(Or am I getting to deep into this :sweat_smile: )

**Comment by terichadbourne** [comment]
@NukeManDan I love that you've noted what to do in case of a conflict of interest. However, my gut feeling is that if someone feels that a leader of your chapter has violated the Code of Conduct, it should be maintainers of the main project that are reached out to, not leaders of other chapters. I'm sure some folks are a bit intimidated by the idea of drafting a CoC and responding to incidents in their own chapter, and I'd prefer not to ask them to take responsibility for other chapters as well.

I'd recommend you give protoschool@protocol.ai as the contact for reporting CoC violations that they're not comfortable reporting to your chapter's organizers. That email list goes to the lead ProtoSchool maintainers (currently myself and @mikeal).  This approach would also prevent you from needing to update your own CoC as the leadership team changes. 

In fact, the best approach might actually be to say something like. "In case of a conflict of interest, or if you feel that this chapter's organizers are not living up to the standards laid out in our Code of Conduct, please follow the reporting procedures laid out in the broader [ProtoSchool Code of Conduct](https://github.com/ProtoSchool/organizing/blob/master/CODE_OF_CONDUCT.md) to reach the project's lead maintainers." That would allow us to change the procedure at the top level without it making your CoC out of date. 

Does this sound reasonable?
